export default {
	COLUMN: 3,
	FRUIT_SPAWN_TIME: 500,
	MAX_FRUIT_SPAWN: 20,
	FRUIT_DROP_SPEED: 5,
	START_LIVES_DEFAULT: 3,
	START_SCORE_DEFAULT: 0,
	CANVAS_HEIGHT: innerHeight,
	CANVAS_WIDTH: 300,
	SCORE_INCREMENT: 10,
} as const;
